
import express from 'express';
import cors from 'cors';
import { GoogleGenAI, Type } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Helper: Get API Key safely
const getApiKey = () => {
  return process.env.API_KEY || process.env.VITE_API_KEY;
};

const apiKey = getApiKey();
if (!apiKey) {
  console.warn("Warning: API_KEY is not set in environment variables.");
}

const ai = new GoogleGenAI({ apiKey });

// Helper: Clean Base64
const cleanBase64 = (base64Data) => {
  return base64Data.split(',')[1] || base64Data;
};

// Helper: Get Mime Type
const getMimeType = (base64Data) => {
  const match = base64Data.match(/^data:([^;]+);base64,/);
  return match ? match[1] : 'image/jpeg';
};

// Helper: Delay
const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// Helper: Retry Logic
async function retryOperation(operation, retries = 10, initialDelay = 2000) {
  let delay = initialDelay;
  for (let i = 0; i < retries; i++) {
    try {
      return await operation();
    } catch (error) {
      const msg = error.message || '';
      const status = error.status || (error.response ? error.response.status : null);
      
      const isRateLimit = status === 429 || msg.includes('429') || msg.includes('exhausted') || msg.includes('quota');
      const isOverloaded = status === 503 || msg.includes('503') || msg.includes('Overloaded');

      if (isRateLimit || isOverloaded) {
        if (i === retries - 1) throw error;
        
        // Jitter
        const jitter = Math.random() * 1000;
        await wait(delay + jitter);
        
        delay = Math.min(delay * 1.5, 15000); // Cap at 15s
        console.warn(`[Server] Retry attempt ${i+1} due to ${isRateLimit ? 'Rate Limit' : 'Overload'}`);
        continue;
      }
      throw error;
    }
  }
}

// --- Routes ---

// 1. Redesign Room
app.post('/api/redesign', async (req, res) => {
  try {
    const { image, style } = req.body;
    if (!image || !style) return res.status(400).json({ error: "Missing image or style" });

    const modelId = 'gemini-2.5-flash-image';
    const mimeType = getMimeType(image);
    
    const prompt = `
      Act as a professional interior designer.
      Redesign the room in the input image to fully embody the '${style}' design style.
      
      REQUIREMENTS:
      1. STRICTLY PRESERVE: Room structure, perspective, window/door placements.
      2. TRANSFORM: Furniture, decor, materials, colors to strictly match '${style}'.
      3. QUALITY: Photorealistic, high definition, natural lighting.
      
      MANDATORY CLEANUP:
      - REMOVE any existing watermarks or text.
      - DO NOT generate any text in the image.
      Return only the generated image.
    `;

    const generatedImage = await retryOperation(async () => {
      const response = await ai.models.generateContent({
        model: modelId,
        contents: {
          parts: [
            { inlineData: { mimeType, data: cleanBase64(image) } },
            { text: prompt }
          ]
        }
      });

      if (response.candidates) {
        for (const candidate of response.candidates) {
          for (const part of candidate.content.parts) {
            if (part.inlineData && part.inlineData.data) {
              return `data:image/png;base64,${part.inlineData.data}`;
            }
          }
        }
      }
      throw new Error("No image generated by model.");
    });

    res.json({ result: generatedImage });
  } catch (error) {
    console.error("[Redesign Error]", error);
    res.status(500).json({ error: error.message || "Failed to generate design" });
  }
});

// 2. Design Advice
app.post('/api/advice', async (req, res) => {
  try {
    const { image, style } = req.body;
    if (!image || !style) return res.status(400).json({ error: "Missing image or style" });

    const modelId = 'gemini-3-flash-preview';
    const mimeType = getMimeType(image);

    const prompt = `
      Analyze this room image for a '${style}' style redesign.
      Provide professional interior design advice in JSON format.
    `;

    const advice = await retryOperation(async () => {
      const response = await ai.models.generateContent({
        model: modelId,
        contents: {
          parts: [
            { inlineData: { mimeType, data: cleanBase64(image) } },
            { text: prompt }
          ]
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              critique: { type: Type.STRING },
              suggestions: { type: Type.ARRAY, items: { type: Type.STRING } },
              colorPalette: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    name: { type: Type.STRING },
                    hex: { type: Type.STRING },
                  },
                  required: ["name", "hex"]
                }
              },
              furnitureRecommendations: { type: Type.ARRAY, items: { type: Type.STRING } }
            },
            required: ["critique", "suggestions", "colorPalette", "furnitureRecommendations"]
          }
        }
      });
      return JSON.parse(response.text || "{}");
    });

    res.json(advice);
  } catch (error) {
    console.error("[Advice Error]", error);
    res.status(500).json({ error: error.message || "Failed to generate advice" });
  }
});

// 3. Shop The Look
app.post('/api/shop', async (req, res) => {
  try {
    const { image } = req.body;
    if (!image) return res.status(400).json({ error: "Missing image" });

    const modelId = 'gemini-3-flash-preview';
    const mimeType = getMimeType(image);

    const prompt = `
      Analyze this room image and identify the key furniture and decor products.
      Return JSON with:
      1. title (string)
      2. style (string)
      3. description (string)
      4. products (array of objects with name, price, category, query, box_2d [ymin, xmin, ymax, xmax])
    `;

    const shopData = await retryOperation(async () => {
      const response = await ai.models.generateContent({
        model: modelId,
        contents: {
          parts: [
            { inlineData: { mimeType, data: cleanBase64(image) } },
            { text: prompt }
          ]
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              style: { type: Type.STRING },
              description: { type: Type.STRING },
              products: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    name: { type: Type.STRING },
                    price: { type: Type.NUMBER },
                    category: { type: Type.STRING },
                    query: { type: Type.STRING },
                    box_2d: { 
                      type: Type.ARRAY, 
                      items: { type: Type.NUMBER }
                    }
                  },
                  required: ["name", "price", "category", "query", "box_2d"]
                }
              }
            },
            required: ["title", "style", "description", "products"]
          }
        }
      });
      return JSON.parse(response.text || "{}");
    });

    res.json(shopData);
  } catch (error) {
    console.error("[Shop Error]", error);
    res.status(500).json({ error: error.message || "Failed to analyze shop items" });
  }
});

// 4. Quiz Description
app.post('/api/quiz-desc', async (req, res) => {
  try {
    const { style } = req.body;
    if (!style) return res.status(400).json({ error: "Missing style" });

    const modelId = 'gemini-3-flash-preview';
    const prompt = `
      Write a captivating, 2-sentence description for an interior design style called "${style}".
      It should sound professional, inviting, and personalized.
    `;

    const text = await retryOperation(async () => {
      const response = await ai.models.generateContent({
        model: modelId,
        contents: { parts: [{ text: prompt }] }
      });
      return response.text || "";
    });

    res.json({ text });
  } catch (error) {
    console.error("[Quiz Error]", error);
    res.status(500).json({ error: error.message || "Failed to generate description" });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
